improved service files
Change-Id: Ie6e24fd29d7a7537ed4d3c43b68cc50b862bc47c

diff --git a/cloudrunner-server.spec.in b/cloudrunner-server.spec.in
--- a/cloudrunner-server.spec.in
+++ b/cloudrunner-server.spec.in
@@ -134,6 +134,12 @@ mkdir -p $RPM_BUILD_ROOT/var/lib/cloudrunner/plugins/
 %clean
 rm -rf %{buildroot}
 
+%post
+if [ -n "$(command -v alembic)" ]; then
+	cd %{python_sitelib}/cloudrunner_server/db/
+	alembic upgrade head || echo "DB upgrade failed"
+fi
+
 %postun
 /sbin/service %{name} condrestart > /dev/null 2>&1 || :
 
