added create_new script to create new DB if empty, added Register command in API
Change-Id: I808b0659cd48363e593faddf4f49d56810439b23

diff --git a/cloudrunner-server.spec.in b/cloudrunner-server.spec.in
--- a/cloudrunner-server.spec.in
+++ b/cloudrunner-server.spec.in
@@ -105,8 +105,13 @@ rm -rf %{buildroot}
 
 %post
 if [ -n "$(command -v alembic)" ]; then
+	VER=$(alembic current --head-only 2>&1 | tail -1)
 	cd %{python_sitelib}/cloudrunner_server/db/
-	alembic upgrade head || echo "DB upgrade failed"
+	if [ "$VER" == "None" ]; then
+		 %{__python} create_new.py
+	else
+		alembic upgrade head || echo "DB upgrade failed"
+	fi
 fi
 
 %postun
